### ISSUE TITLE
roslaunch tests feil for cob_hardware_tests if no environment variables are set

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#115]
Our new jenkins server reports build failures for the roslaunch tests in cob_hardware_test. Please use the <arg name="robot"/> tags in the tests (similar to the launch files in cob_bringup).

use "unset ROBOT" and "unset ROBOT_ENV" and then do a "make test" in cob_hardware_test to reproduce the error.

**Comment by ipa-fmw-ms** [comment]
I have the following Problem with make test and arg:
http://answers.ros.org/question/38241/rosbuild_add_roslaunch_check-fails-for-included-files-using-launch-file-arguments/

**Comment by fmessmer** [comment]
I think this is no longer an issue as all tests pass with #279 - even with `ROBOT` and `ROBOT_ENV` unset!
Thus, I think we can close this!
