### ISSUE TITLE
wrong reference values for schunk arms

### ISSUE THREAD

**Issue by ipa-rmb** [ipa320/cob_robots#130]
There are wrong reference values for arm_6_joint in all cob3's with schunk arm (cob3-2, cob3-5, cob3-6)!
They are way too large and lead to controller error (>0.15)

Query the correct values from the respective robot hardware!

**Comment by ipa-rmb** [comment]
@ipa-fxm

**Comment by floweisshardt** [comment]
the reference offsets are probably wrong in cob_robots https://github.com/ipa320/cob_robots/blob/groovy_dev/cob_hardware_config/cob3-2/urdf/calibration_default.urdf.xacro#L94 (same for cob3-5 and cob3-6)

solution: use windows schunk software to set firmware offsets to -pi to pi and then adapt refrence offset in calibration _default

**Comment by floweisshardt** [comment]
seems to be solved
