### ISSUE TITLE
Change from canopen executable

### ISSUE THREAD

**Issue by thiagodefreitas** [ipa320/cob_robots#164]
@ipa-fmw , @ipa-nhg . Please be aware that the canopen executable name has changed in Hydro to ipa_canopen_ros instead of canopen_ros. This was the cause of the issue in cob3-3.

**Comment by floweisshardt** [comment]
@ipa-nhg: can you please check that in cob_bringup?

**Comment by fmessmer** [comment]
This seems to be correct already:
https://github.com/ipa320/cob_robots/blob/hydro_dev/cob_bringup/drivers/canopen_driver.launch

**Comment by NadiaHG** [comment]
Tested on cob4-1 : OK
