### ISSUE TITLE
Add parameter to cob_hardware_config

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#207]
https://github.com/ipa320/cob_driver/pull/148 introduced new parameters
- max_trans_velocity
- max_rot_velocity

Currently they are not set within any yaml file, thus the hasParam-check fails and the default value is used. It would be good to know in which yaml these parameters can be set (in cob_hardware_config?). There should be a respective entry in the according yaml for all robots (using the same default value as in the code)
--> reduces output when starting bringup/bringup_sim

@ipa-frm

**Comment by fmessmer** [comment]
Ping?

**Comment by mgruhler** [comment]
@ipa-fxm Those parameters would need to go into the launch file, as there is currently no yaml file set for the undercarriage_ctrl...

https://github.com/ipa320/cob_robots/blob/hydro_dev/cob_bringup/controllers/base_controller.launch

I'll put it on my list

**Comment by floweisshardt** [comment]
As the undercarriage_ctrl node currently still has the ini-file structure,we will do this once we got rid of the ini files. Espacially since those two parameters are only the absolute upper limit for avoiding the "racing robot bug", see https://github.com/ipa320/cob_robots/pull/233

**Comment by fmessmer** [comment]
@ipa-mig:
ping

**Comment by floweisshardt** [comment]
as cob_undercarriage_ctrl is outdated and replaced by the ros_control implementation for all new bases, I'll vote for not spending effort on this issue.

can be closed then

**Comment by mgruhler** [comment]
the question remains how we will handle this. We still need this for the rob@work and CoB3 robots...
+1 for not spending too much effort on this, however, we should discuss how to proceed...

**Comment by fmessmer** [comment]
Well as #233 has been merge for a while now and no complains occurred about any robot driving too fast/slow...I think it is ok just leaving those default values...and consider this fixed...
no more effort for putting the parameter from launch file to yaml!
