### ISSUE TITLE
if emergency stop button is active initialisation return success

### ISSUE THREAD

**Issue by destogl** [ipa320/cob_robots#227]
I tried to initialize platform with joystick when emergency stop button was active and even there is an error in communication with motors there is ROS-INFO output about success of initialization.

**Comment by floweisshardt** [comment]
this probably needs to be fixed in cob_driver/cob_base_drive_chain. @ipa-mig and @abubeck can you confirm this behaviour?

**Comment by mgruhler** [comment]
I can confirm this behaviour. Will fix it, as soon as I have the time...
However, I am currently not sure, what packages need to be checked. I think everything from base_drive_chain down (i.e. probably until the CAN nodes...)

IMO, the biggest problem is not even the output, but rather that the platform considers itself initialized and you cannot reinitialize it again without restarting the bringup level...

**Comment by mgruhler** [comment]
the problem was just the output. Nothing wrong with the initialization behaviour in the base_drive_chain. Bugfixes in respective PRs referenced above

**Comment by destogl** [comment]
Thanks for reparing :+1:

**Comment by mgruhler** [comment]
Not merged yet ;-)

Von: Denis Štogl [mailto:notifications@github.com]
Gesendet: Dienstag, 10. Februar 2015 11:14
An: ipa320/cob_robots
Cc: Gruhler, Matthias
Betreff: Re: [cob_robots] if emergency stop button is active initialisation return success (#227)

Thanks for reparing [:+1:]
