### ISSUE TITLE
add action_name and service_ns for all robots in cob_default_robot_config

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#242]
for new structure:
action_name: /arm_left/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm_left/driver

for old structure
action_name: /arm_left_controller/follow_joint_trajectory
service_ns: /arm_left_controller

**Comment by NadiaHG** [comment]
Done https://github.com/ipa320/cob_robots/pull/244
