### ISSUE TITLE
add mimic launch file in cob_bringup

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#283]
see https://github.com/ipa320/cob4/issues/179

**Comment by NadiaHG** [comment]
https://github.com/ipa320/cob_robots/pull/285

**Comment by fmessmer** [comment]
what's the status here?
I've seen the launch file on the robot but it's not in the repository yet....probably due to the [comments](https://github.com/ipa320/cob_robots/pull/285#discussion-diff-26847895)?

**Comment by fmessmer** [comment]
As the launch file has been added a while ago, and now also the [comment](https://github.com/ipa320/cob_robots/pull/285#discussion-diff-26847895) about unifying topic/service/action names of mimic, sound andd lights is considered in https://github.com/ipa320/cob_driver/pull/223, https://github.com/ipa320/cob_robots/pull/296 and https://github.com/ipa320/cob_command_tools/pull/98, this can be closed
