### ISSUE TITLE
Calbrate cob4-1 and cob4-2 Asus Xtion cameras

### ISSUE THREAD

**Issue by NadiaHG** [ipa320/cob_robots#372]
add the configuration files to https://github.com/ipa320/cob_calibration_data/tree/indigo_dev/cob4-1/calibration/cameras

**Comment by fmessmer** [comment]
~~might be related: https://github.com/ipa320/cob_calibration/issues/10~~

When calibrated also consider https://github.com/ipa320/cob_calibration_data/issues/99

**Comment by fmessmer** [comment]
@ipa-nhg what about this issue?
cob4-1 is obsolete...but do we normally calibrate the asus xtion cameras (I guess its the torso_left and torso_right)

**Comment by NadiaHG** [comment]
this can be closed, we are not calibrating the asus cameras, and cob4-1 and cob4-2 are obsoletes.
