### ISSUE TITLE
Add launch file checks and URDF checks

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#374]
We need to write these tests and add them to travis

@ipa-fmw @ipa-mdl 
Do you have a good idea how to deal with the problem about using `$(find )` and `$(arg )` and such mixed together?

**Comment by fmessmer** [comment]
@ipa-mdl:
rosinstall template https://github.com/ipa320/setup/blob/master/repositories/cob_indigo_bringup.rosinstall

**Comment by fmessmer** [comment]
Sweet!
Let's bring this new travis configuration to the other repos as well - after the merge session on Tuesday!

**Comment by fmessmer** [comment]
We might need to update/recheck the `robotlist` entries in e.g. `cob_bringup`, `cob_controller_configuration_gazebo`, `cob_gazebo`,...

**Comment by mathias-luedtke** [comment]
It would be even better to keep a consolidated list at one single place. It could be a symlinked cmake files that is included or we could keep the list in a  dedicated package (e.g. cob_robot_list) and expose it to dependent packages (`CFG_EXTRAS`).
