### ISSUE TITLE
[ctitical] implement cob_default_robot_behaviour using handles

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#387]
especially for torso movements and pick movements, we should check every command using the handles and abort if a previous movement cannot be completed as expected! 

```
handle = sss.move()
handle.wait()
if handle.get_error_code() != 0:
   ABORT
```
- define a handle for each `sss.move` command
- wait for movements to be finished before executing new movements
- do NOT use `spleep()` to synchronize movements (which can cause a collission)
- only continue if error_code is zero (==0)

This is currently missing for pick! ...disabling this button for now in the robot dashboard!

**Comment by fmessmer** [comment]
fixed in #411
