### ISSUE TITLE
remove canX.yaml files and integrate into component specific yaml files

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#420]
currently can0.yaml is used on the base pc for the base and on the torso pc for the arms/sensorring/torso. If we keep a common can0.yaml we cannot have different CAN configurations for e.g. base and torso.

@ipa-mdl had some suggestion how to restructure

**Comment by mathias-luedtke** [comment]
- move all params into the driver yaml
- but set `bus/device` from the launch file

**Comment by fmessmer** [comment]
solved in #435
