### ISSUE TITLE
[cob_bringup] env.sh as env-loader script

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#461]
@ipa-nhg @ipa-fmw

This is evolving from https://github.com/ipa320/cob_robots/pull/459#issuecomment-205390813

Beside the discussion about what to do about `env.sh`, the following things need to be done (@ipa-nhg)
- [ ] accounts need to be generated for all users that have an account on the base-pc
- [ ] perform `ssh-copy-id` and make sure there is a valid `.bashrc` (cob_default.bashrc is fine) that is sourced

**Comment by fmessmer** [comment]
The problem is that we cannot use `$(find cob_bringup)` within the `env-loader` part of the `machine`-tag as it gets resolved **before** being passed to the remote PC!

Thus, if an overlay of `cob_robots` exists on the b1-PC, "/u/user-name/git/care-o-bot/src/cob_robots/cob_bringup/env.sh" is passed over to the remote PC, e.g. h32. 
However, if no overlay exists on the remote-PC, this file does not exist, and `cob_bringup/robot.launch` will fail...

In #462, I tried to make the env-loader-script a launch argument and tried to use `~/.bashrc` which is a relative path and could be resolved to the remote-PCs local `.bashrc` which can be different from the b1-PC `.bashrc`....

However, according to [here](http://wiki.ros.org/roslaunch/XML/machine) the env-script needs to be a shell script. (Passing `~/.bashrc` fails with

```
fxm@cob4-2-b1:~$ roslaunch cob_bringup robot.launch robot:=cob4-1
... logging to /u/fxm/.ros/log/eb99b746-fc8e-11e5-b1a9-eca86bff61c1/roslaunch-cob4-2-b1-9337.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/u/fxm/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://cob4-2-b1:46077/
remote[cob4-2-t2-0] starting roslaunch
remote[cob4-2-t2-0]: creating ssh connection to cob4-2-t2:22
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://cob4-2-b1:11311 /u/fxm/git/care-o-bot/src/cob_robots/cob_bringup/env.sh roslaunch -c cob4-2-t2-0 -u http://cob4-2-b1:46077/ --run_id eb99b746-fc8e-11e5-b1a9-eca86bff61c1]
remote[cob4-2-t2-0]: ssh connection created
remote[cob4-2-t1-1] starting roslaunch
remote[cob4-2-t1-1]: creating ssh connection to cob4-2-t1:22
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://cob4-2-b1:11311 /u/fxm/git/care-o-bot/src/cob_robots/cob_bringup/env.sh roslaunch -c cob4-2-t1-1 -u http://cob4-2-b1:46077/ --run_id eb99b746-fc8e-11e5-b1a9-eca86bff61c1]
remote[cob4-2-t1-1]: ssh connection created
remote[cob4-2-h32-2] starting roslaunch
remote[cob4-2-h32-2]: creating ssh connection to cob4-2-h32:22
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://cob4-2-b1:11311 ~/.bashrc roslaunch -c cob4-2-h32-2 -u http://cob4-2-b1:46077/ --run_id eb99b746-fc8e-11e5-b1a9-eca86bff61c1]
remote[cob4-2-h32-2]: ssh connection created
remote[cob4-2-s1-3] starting roslaunch
remote[cob4-2-s1-3]: creating ssh connection to cob4-2-s1:22
remote[cob4-2-h32-2]: env: /u/fxm/.bashrc: Permission denied

[cob4-2-h32-2] process has died
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://cob4-2-b1:11311 /u/fxm/git/care-o-bot/src/cob_robots/cob_bringup/env.sh roslaunch -c cob4-2-s1-3 -u http://cob4-2-b1:46077/ --run_id eb99b746-fc8e-11e5-b1a9-eca86bff61c1]
remote[cob4-2-s1-3]: ssh connection created
remote[cob4-2-t3-4] starting roslaunch
remote[cob4-2-t3-4]: creating ssh connection to cob4-2-t3:22
launching remote roslaunch child with command: [env ROS_MASTER_URI=http://cob4-2-b1:11311 /u/fxm/git/care-o-bot/src/cob_robots/cob_bringup/env.sh roslaunch -c cob4-2-t3-4 -u http://cob4-2-b1:46077/ --run_id eb99b746-fc8e-11e5-b1a9-eca86bff61c1]
remote[cob4-2-t3-4]: ssh connection created
[cob4-2-t3-4] killing on exit
[cob4-2-s1-3] killing on exit
[cob4-2-t1-1] killing on exit
[cob4-2-t2-0] killing on exit
remote roslaunch failed to launch: cob4-1-h1
The traceback for the exception was written to the log file
```

**Comment by fmessmer** [comment]
I don't have a good solution yet, but maybe we could put the `env.sh` from `cob_bringup` into a folder that can be accessed by all users, e.g. `/opt/care-o-bot`.
We would need to put this file there when setting up a PC afresh...or let the robot users install the `env.sh` into this folder instead of into [`${CATKIN_PACKAGE_SHARE_DESTINATION}`](https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/CMakeLists.txt#L48-L50)

**Comment by NadiaHG** [comment]
If I understood right , please @ipa-fmw correct me if I am wrong, the use of a 32 bits machine is temporal. The issue with the sound driver and 64 linux system should be solved soon. I don't think that make sense put  effort on that. what about use for the moment the `/opt/ros/indigo/env.sh` ?? or the release version of cob_sound is out-of-date?

My upstart installation also create a env.sh file, that with a full cob installation will be copied to `/etc/ros/$ROS_DISTRO/cob.d/setup/cob.d/setup/env.sh` for all the cob-pcs : https://github.com/ipa320/setup_cob4/blob/master/upstart/upstart_install.sh#L30 . But some modifications will be needed to use it. And from my point of view, is not nice use a global path (hardcoded) on cob_bringup....robot.xml

**Comment by fmessmer** [comment]
Has this been solved?
Still using the 32bit machine? What about user management?
@ipa-nhg please comment and close (if applicable)

**Comment by floweisshardt** [comment]
in cob4-7 we're not using a 32-bit ubuntu on the head pc any more.

**Comment by fmessmer** [comment]
I guess then this can be closed...

**Comment by NadiaHG** [comment]
It can be closed. Actually it is already done, it was needed in case that you source a different workspace and start something remotely, for further info see https://github.com/ipa320/cob_robots/pull/537
