### ISSUE TITLE
[setup raw3-1]Find out the phidgets serial on raw3-1

### ISSUE THREAD

**Issue by NadiaHG** [ipa320/cob_robots#483]

**Comment by fmessmer** [comment]
Seems to be fixed (https://github.com/ipa320/cob_robots/pull/475/files#diff-c3c1576e01fb1063d4a430245c2480d6R6)
@ipa-nhg @ipa-bnm please close

**Comment by fmessmer** [comment]
we will receive an updated raw3-1 config by @ipa-bfb soon anyway
