### ISSUE TITLE
remove softkinetic from bringup

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#516]
there's no robot which uses softkinetic anymore, so we can get rid of the dependency.

**Comment by floweisshardt** [comment]
@ipa-nhg: do you know any of our robots still using softkinetic?

**Comment by fmessmer** [comment]
softkinetic seems to be removed completely in https://github.com/ipa320/cob_robots/commit/badd35106f68524b60b019f52a0bcef399f7313b#diff-a2c8ca93cf7d49250f0b3e480c8fc453
@ipa-nhg please comment and close

**Comment by NadiaHG** [comment]
Yes, it is done, the issue can be closed.
