### ISSUE TITLE
check image flip with mode=1 for head_cam

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#546]
see comments in https://github.com/ipa320/cob_robots/pull/541#pullrequestreview-3712086

**Comment by fmessmer** [comment]
mode=1 seems to be used https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_hardware_config/cob4-2/config/image_flip_params_head_cam.yaml#L3

Is this behavior satisfying?
@ipa-fmw @ipa-nhg please comment and close

**Comment by NadiaHG** [comment]
Can be closed, @ipa-rmb solved the problem with this PR: https://github.com/ipa320/cob_perception_common/commit/61312f7ad5e501fb40b020b99e322caea3f01f6a
