### ISSUE TITLE
[Enhancement] Update xacro's according to latest syntax

### ISSUE THREAD

**Issue by fmessmer** [ipa320/cob_robots#563]
as done in https://github.com/ipa320/schunk_modular_robotics/pull/171

as documented in [xacro](http://wiki.ros.org/xacro#Property_and_Property_Blocks)

affects:
 - xacro:include
 - xacro:property
 - xacro:insert_block
 - xacro:arg
 - xacro:if/xacro:unless

apply these changes to __all__ xacro-files (cob_calibration_data, cob_common, cob_robots,....etc.)

Use the [helper command](http://wiki.ros.org/xacro#Deprecated_Syntax)
```
find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
```

**Comment by mathias-luedtke** [comment]
Please do not forget to pull in the xacro namespace in the root element:
```<robot xmlns:xacro="http://www.ros.org/wiki/xacro">```

**Comment by fmessmer** [comment]
only cob_robots missing...

**Comment by ipa-fmw** [comment]
merged and done
