### ISSUE TITLE
cob3-6 files missing

### ISSUE THREAD

**Issue by bbrito** [ipa320/cob_robots#606]
We are still working with cob3-6. The robot is fully operational and with Indigo. We should keep its configuration.

**Comment by bbrito** [comment]
@ipa-fxm should I try to add the files to the current version of indigo dev of cob3-6?

**Comment by ipa-bfb-sc** [comment]
@ipa-fmw @ipa-bfb @ipa-fxm  why did we finish with cob3-6 configuration if we still have one operational?

**Comment by bbrito** [comment]
@ipa-bfb-sc is already taking care of it

**Comment by floweisshardt** [comment]
is there any decision here how we continue with cob3-6 and cob3's in general? @ipa-bfb: please get feedback from BTG

**Comment by bbrito** [comment]
BTG said that we should discuss this on a meeting Monday. Do you have any free time?

**Comment by floweisshardt** [comment]
decision is to not merge the cob3-6 config back to indigo_dev, so I'll close this issue
