### ISSUE TITLE
Error while doing moveit setup assistance

### ISSUE THREAD

**Issue by mjpatell** [ipa320/cob_robots#682]
Hello,

I am getting below error when I was doing moveit setup assistance for care-o-bot4. For moveit setup assistance, I am loading cob4-5.urdf.xacro. Any one can help me to get rid of this error.

![error moveit_setup_assistance](https://user-images.githubusercontent.com/28396588/28238203-ff170548-694e-11e7-80a2-c1c81780ab63.png)

Thank you.

**Comment by fmessmer** [comment]
duplicate of https://github.com/ipa320/cob_manipulation/issues/105...

**Comment by fmessmer** [comment]
for the time being simply run:
`rosrun xacro xacro --inorder raw3-1.urdf.xacro > raw3-1.urdf`
within `cob_hardware_config/robots/raw3-1/urdf` then load the urdf  - and not the xacro from the setup assistant...

**Comment by bbrito** [comment]
We want to create the moveit config for cob4 not raw3-1.

Is it the same procedure?
